# Generated by Django 5.2.11 on 2026-08-03 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author_studio', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manuscript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('IN_REVIEW', 'In review'), ('APPROVED', 'Approved'), ('PROMOTED', 'Promoted')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('work', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='writer_manuscript', to='author_studio.work')),
            ],
        ),
        migrations.CreateModel(
            name='ManuscriptVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('change_note', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manuscript', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='writer.manuscript')),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='WriterPromotionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editor_approval', models.CharField(max_length=150)),
                ('promoted_sha256', models.CharField(max_length=64)),
                ('previous_canonical_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('previous_canonical_path', models.CharField(blank=True, default='', max_length=500)),
                ('outcome', models.CharField(default='PROMOTED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manuscript', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotion_events', to='writer.manuscript')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotion_events', to='writer.manuscriptversion')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='manuscriptversion',
            constraint=models.UniqueConstraint(fields=('manuscript', 'version'), name='writer_unique_version'),
        ),
    ]
