# Generated by Django 5.2.11 on 2026-08-03 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author_studio', '__first__'),
        ('editorial', '0019_editionbuild_validation_report'),
        ('writer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='writerpromotionevent',
            name='actor',
            field=models.CharField(default='system', max_length=150),
        ),
        migrations.AddField(
            model_name='writerpromotionevent',
            name='new_canonical_path',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='writerpromotionevent',
            name='reason',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.CreateModel(
            name='EditorialWorkLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linked_by', models.CharField(max_length=150)),
                ('reason', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author_work', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='editorial_identity_link', to='author_studio.work')),
                ('editorial_work', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='writer_identity_link', to='editorial.work')),
            ],
        ),
    ]
