"""Deterministic LaTeX source generation for print interiors."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Iterable

from .specs import PrintSpec


_LATEX_ESCAPES = {
    "\\": r"\textbackslash{}",
    "&": r"\&",
    "%": r"\%",
    "$": r"\$",
    "#": r"\#",
    "_": r"\_",
    "{": r"\{",
    "}": r"\}",
    "~": r"\textasciitilde{}",
    "^": r"\textasciicircum{}",
}


def escape_latex(text: str) -> str:
    return "".join(_LATEX_ESCAPES.get(char, char) for char in text)


def _paragraphs(text: str) -> str:
    blocks = [block.strip() for block in text.replace("\r\n", "\n").split("\n\n")]
    return "\n\n".join(escape_latex(block.replace("\n", " ")) for block in blocks if block)


@dataclass(frozen=True)
class Chapter:
    title: str
    body: str


@dataclass(frozen=True)
class BookContent:
    title: str
    author: str
    chapters: tuple[Chapter, ...]
    subtitle: str = ""
    language: str = "en-US"
    publisher: str = "RinoBooks"
    copyright_text: str = ""

    @classmethod
    def from_chapters(
        cls,
        *,
        title: str,
        author: str,
        chapters: Iterable[Chapter],
        subtitle: str = "",
        language: str = "en-US",
        publisher: str = "RinoBooks",
        copyright_text: str = "",
    ) -> "BookContent":
        return cls(
            title=title,
            author=author,
            chapters=tuple(chapters),
            subtitle=subtitle,
            language=language,
            publisher=publisher,
            copyright_text=copyright_text,
        )


class LatexInteriorRenderer:
    """Render a no-bleed trade-book interior for LuaLaTeX.

    v1 intentionally refuses bleed interiors instead of producing subtly wrong
    asymmetric bleed geometry.  Novels and most text-first RinoBooks editions
    use no-bleed interiors, so this keeps the first production path safe.
    """

    def render(self, content: BookContent, spec: PrintSpec) -> str:
        if spec.interior_bleed:
            raise ValueError("print-engine v1 does not yet compose bleed interiors")
        if not content.chapters:
            raise ValueError("at least one chapter is required")

        trim_w = str(spec.trim_width_in)
        trim_h = str(spec.trim_height_in)
        safe = str(spec.interior_safe_margin_in)
        font_size = str(spec.body_font_size_pt)
        leading = str(spec.body_leading_pt)
        font = escape_latex(spec.body_font)

        chapter_tex = []
        for chapter in content.chapters:
            chapter_tex.append(
                "\\chapter{" + escape_latex(chapter.title) + "}\n" + _paragraphs(chapter.body)
            )

        subtitle = escape_latex(content.subtitle)
        title_block = escape_latex(content.title)
        if subtitle:
            title_block += r"\\[0.7em]{\large " + subtitle + "}"

        copyright_text = content.copyright_text.strip()
        if not copyright_text:
            copyright_text = f"Published by {content.publisher}."

        return f"""% Generated by Gaiden Print Engine. Do not hand-edit generated output.
\\documentclass[11pt,twoside,openright]{{memoir}}
\\usepackage{{fontspec}}
\\usepackage{{microtype}}
\\usepackage{{geometry}}
\\usepackage{{setspace}}
\\geometry{{paperwidth={trim_w}in,paperheight={trim_h}in,inner={safe}in,outer={safe}in,top={safe}in,bottom={safe}in}}
\\setmainfont{{{font}}}
\\setlength{{\\parindent}}{{1.25em}}
\\setlength{{\\parskip}}{{0pt}}
\\clubpenalty=10000
\\widowpenalty=10000
\\displaywidowpenalty=10000
\\raggedbottom
\\makepagestyle{{gaiden}}
\\makeevenhead{{gaiden}}{{\\small\\thepage}}{{}}{{\\small\\leftmark}}
\\makeoddhead{{gaiden}}{{\\small\\rightmark}}{{}}{{\\small\\thepage}}
\\makeevenfoot{{gaiden}}{{}}{{}}{{}}
\\makeoddfoot{{gaiden}}{{}}{{}}{{}}
\\pagestyle{{gaiden}}
\\begin{{document}}
\\fontsize{{{font_size}pt}}{{{leading}pt}}\\selectfont
\\frontmatter
\\thispagestyle{{empty}}
\\vspace*{{\\fill}}
\\begin{{center}}
{{\\Huge {title_block}}}\\\\[2em]
{{\\large {escape_latex(content.author)}}}
\\end{{center}}
\\vspace*{{\\fill}}
\\clearpage
\\thispagestyle{{empty}}
\\vspace*{{\\fill}}
\\noindent {escape_latex(copyright_text)}
\\clearpage
\\mainmatter
{chr(10).join(chapter_tex)}
\\backmatter
\\cleardoublepage
\\thispagestyle{{empty}}
\\vspace*{{\\fill}}
\\begin{{center}}The End\\end{{center}}
\\vspace*{{\\fill}}
\\end{{document}}
"""
