# Generated by Django 5.2.10 on 2026-01-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=10)),
                ('stage', models.CharField(choices=[('normalize', 'Normalize'), ('split', 'Split'), ('translate', 'Translate'), ('polish', 'Polish'), ('merge', 'Merge'), ('build', 'Build EPUB/PDF')], max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('RUNNING', 'Rodando'), ('SUCCESS', 'Sucesso'), ('FAIL', 'Falhou')], default='PENDING', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
