# Generated by Django 5.2.10 on 2026-01-13 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pipelinejob',
            options={'ordering': ['book_code', 'language', 'stage']},
        ),
        migrations.RenameField(
            model_name='pipelinejob',
            old_name='book_name',
            new_name='book_title',
        ),
        migrations.AddField(
            model_name='pipelinejob',
            name='book_code',
            field=models.CharField(default='book_0001', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pipelinejob',
            name='filepath',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pipelinejob',
            name='stage',
            field=models.CharField(choices=[('normalize', 'Normalize'), ('split', 'Split'), ('translate', 'Translate'), ('refine', 'Refine'), ('polish', 'Polish')], max_length=50),
        ),
    ]
