# Generated by Django 5.2.10 on 2026-01-13 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0002_alter_pipelinejob_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipelinejob',
            name='stage',
            field=models.CharField(choices=[('raw', 'Raw'), ('normalize', 'Normalize'), ('split', 'Split'), ('translate', 'Translate'), ('refine', 'Refine'), ('polish', 'Polish')], max_length=50),
        ),
        migrations.CreateModel(
            name='BookEditionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_code', models.CharField(db_index=True, max_length=64)),
                ('language', models.CharField(choices=[('en', 'English'), ('ptbr', 'Portugues (Brasil)'), ('es', 'Espanol'), ('de', 'Deutsch')], default='en', max_length=8)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('author_name', models.CharField(max_length=255)),
                ('publication_year', models.IntegerField()),
                ('collaborator_name', models.CharField(blank=True, max_length=255)),
                ('collaborator_pseudonym', models.CharField(blank=True, max_length=255)),
                ('collaborator_roles', models.CharField(blank=True, help_text='Roles separated by comma: translator,adapter,curator,revisor,author', max_length=255)),
                ('frontispiece_text', models.TextField(blank=True)),
                ('copyright_text', models.TextField(blank=True)),
                ('about_edition_text', models.TextField(blank=True)),
                ('about_contributor_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['book_code', 'language'],
                'unique_together': {('book_code', 'language')},
            },
        ),
    ]
