# Generated by Django 5.2.10 on 2026-01-14 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0003_alter_pipelinejob_stage_bookeditiontemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookeditiontemplate',
            name='collection_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='bookeditiontemplate',
            name='cover_filepath',
            field=models.CharField(blank=True, help_text='Path inside the project (e.g., data/covers/book_0001/en/cover.jpg).', max_length=500, verbose_name='Cover file path'),
        ),
        migrations.AddField(
            model_name='bookeditiontemplate',
            name='images_dir',
            field=models.CharField(blank=True, help_text='Folder with book images (e.g., data/images/book_0001/en/).', max_length=500, verbose_name='Images folder path'),
        ),
        migrations.AddField(
            model_name='bookeditiontemplate',
            name='imprint_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
