# Generated by Codex on 2026-01-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0004_bookeditiontemplate_collection_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookeditiontemplate",
            name="collaborator_roles",
            field=models.CharField(
                blank=True,
                help_text=(
                    "Roles separated by comma: translator,adapter,curator,revisor,publisher,author"
                ),
                max_length=255,
            ),
        ),
    ]
