# Generated by Codex on 2026-01-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0005_alter_bookeditiontemplate_collaborator_roles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookeditiontemplate",
            name="collaborator_roles",
            field=models.CharField(
                blank=True,
                help_text=(
                    "Roles separated by comma: translator,adapter,curator,revisor,publisher,"
                    "author,preface,introduction,epilogue,illustrator"
                ),
                max_length=255,
            ),
        ),
    ]
