# Generated by Django 5.2.10 on 2026-01-20 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0010_bookeditiontemplate_city_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookeditiontemplate',
            name='language',
            field=models.CharField(choices=[('en', 'en'), ('es', 'es'), ('ptbr', 'pt-br'), ('de', 'Deutsch')], default='en', max_length=8),
        ),
    ]
