# Generated by Codex on 2026-02-06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0013_bookeditiontemplate_copyright_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="PipelineRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("mode", models.CharField(choices=[("MATRIX", "Matrix")], default="MATRIX", max_length=20)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("TRANSLATE", "Translate"),
                            ("SPLIT", "Split"),
                            ("RETURN_REFINE", "Return Refine"),
                            ("BUILD", "Build"),
                        ],
                        default="TRANSLATE",
                        max_length=30,
                    ),
                ),
                ("options", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendente"),
                            ("RUNNING", "Rodando"),
                            ("DONE", "Concluido"),
                            ("FAILED", "Falhou"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PipelineRunItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("book_id", models.IntegerField(blank=True, null=True)),
                ("book_code", models.CharField(blank=True, max_length=50)),
                ("lang", models.CharField(max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendente"),
                            ("RUNNING", "Rodando"),
                            ("DONE", "Ok"),
                            ("FAILED", "Falhou"),
                            ("SKIPPED", "Pulado"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("out_path", models.TextField(blank=True)),
                ("log_path", models.TextField(blank=True)),
                ("skipped_reason", models.TextField(blank=True)),
                ("overwrote", models.BooleanField(default=False)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="pipeline.pipelinerun",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
