# Generated by Django 5.2.10 on 2026-02-06 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0014_pipelinerun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookeditiontemplate',
            name='language',
            field=models.CharField(choices=[('en', 'en'), ('es', 'es'), ('ptbr', 'pt-br'), ('de', 'Deutsch'), ('fr', 'fr'), ('it', 'it')], default='en', max_length=8),
        ),
        migrations.AlterField(
            model_name='pipelinejob',
            name='stage',
            field=models.CharField(choices=[('raw', 'Raw'), ('normalize', 'Normalize'), ('chunk', 'Chunk'), ('translate', 'Translate'), ('refine', 'Refine'), ('polish', 'Polish')], max_length=50),
        ),
        migrations.AlterField(
            model_name='pipelinerun',
            name='action',
            field=models.CharField(choices=[('TRANSLATE', 'Translate'), ('SPLIT_FOR_REFINE', 'Split for Refine'), ('RETURN_REFINE', 'Return Refine'), ('BUILD', 'Build')], default='TRANSLATE', max_length=30),
        ),
    ]
