# Generated by Django 5.2.11 on 2026-03-27 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0014_bookeditiontemplate_registration_upload_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookeditiontemplate',
            name='epilogue_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bookeditiontemplate',
            name='has_epilogue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookeditiontemplate',
            name='has_introduction',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookeditiontemplate',
            name='has_preface',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookeditiontemplate',
            name='introduction_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bookeditiontemplate',
            name='preface_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='bookeditiontemplate',
            name='language',
            field=models.CharField(choices=[('en', 'en'), ('es', 'es'), ('ptbr', 'pt-br'), ('de', 'Deutsch'), ('fr', 'Français'), ('it', 'Italiano')], default='en', max_length=8),
        ),
    ]
