# Generated by Django 5.2.10 on 2026-02-08 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0015_alter_bookeditiontemplate_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipelinerun',
            name='action',
            field=models.CharField(choices=[('NORMALIZE', 'Normalize'), ('CHUNK', 'Chunk'), ('TRANSLATE', 'Translate'), ('SPLIT_FOR_REFINE', 'Split for Refine'), ('RETURN_REFINE', 'Return Refine'), ('BUILD', 'Build')], default='TRANSLATE', max_length=30),
        ),
    ]
