# Generated by Django 5.2.10 on 2026-02-23 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0018_pipelinerunstate_modes_and_md_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipelinerun',
            name='action',
            field=models.CharField(choices=[('NORMALIZE', 'Normalize'), ('CHUNK', 'Chunk'), ('TRANSLATE', 'Translate'), ('SPLIT_FOR_REFINE', 'Split for Refine'), ('RETURN_REFINE', 'Return Refine'), ('BUILD', 'Build'), ('EXPORT_EPUB', 'Export EPUB')], default='TRANSLATE', max_length=30),
        ),
    ]
