# Generated by Django 5.2.11 on 2026-08-24 21:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


def backfill_distinct_correlation_ids(apps, schema_editor):
    ManualTranslationJob = apps.get_model('pipeline', 'ManualTranslationJob')
    for job_id in ManualTranslationJob.objects.values_list('id', flat=True).iterator():
        ManualTranslationJob.objects.filter(id=job_id).update(correlation_id=str(uuid.uuid4()))


class Migration(migrations.Migration):

    dependencies = [
        ('editorial', '0021_pipelineartifact_sha256_alter_pipelineartifact_stage'),
        ('pipeline', '0020_productionbookmark_immutable'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationJobEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(max_length=48)),
                ('previous_status', models.CharField(blank=True, default='', max_length=32)),
                ('new_status', models.CharField(max_length=32)),
                ('origin', models.CharField(default='gaiden', max_length=32)),
                ('correlation_id', models.CharField(db_index=True, max_length=64)),
                ('error', models.TextField(blank=True, default='')),
                ('detail', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='TranslationUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_id', models.CharField(max_length=32)),
                ('sequence', models.PositiveIntegerField()),
                ('unit_type', models.CharField(choices=[('preliminaries', 'Preliminares'), ('preface', 'Prefácio'), ('introduction', 'Introdução'), ('chapter', 'Capítulo'), ('epilogue', 'Epílogo'), ('appendix', 'Apêndice'), ('oversized_chapter_part', 'Parte de capítulo superdimensionado')], max_length=32)),
                ('chapter_number', models.CharField(blank=True, default='', max_length=32)),
                ('part_number', models.PositiveIntegerField(blank=True, null=True)),
                ('heading', models.CharField(blank=True, default='', max_length=500)),
                ('source_start_offset', models.PositiveBigIntegerField()),
                ('source_end_offset', models.PositiveBigIntegerField()),
                ('source_text_sha256', models.CharField(max_length=64)),
                ('source_size_bytes', models.PositiveBigIntegerField()),
                ('input_filename', models.CharField(max_length=500)),
                ('expected_return_filename', models.CharField(max_length=500)),
                ('drive_input_file_id', models.CharField(blank=True, default='', max_length=255)),
                ('drive_return_file_id', models.CharField(blank=True, default='', max_length=255)),
                ('return_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('return_size_bytes', models.PositiveBigIntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('SPLIT', 'Separada'), ('EXPORTED', 'Exportada'), ('RETURNED', 'Retornada'), ('VALIDATED', 'Validada'), ('FAILED_RETRYABLE', 'Falha recuperável'), ('CONFLICT', 'Conflito'), ('REJECTED', 'Rejeitada')], default='PENDING', max_length=24)),
                ('validation_report', models.JSONField(default=dict)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('translation_job_id', 'sequence'),
            },
        ),
        migrations.AddField(
            model_name='manualtranslationjob',
            name='chapter_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='manualtranslationjob',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manualtranslationjob',
            name='correlation_id',
            field=models.CharField(db_index=True, default=uuid.uuid4, editable=False, max_length=64),
        ),
        migrations.RunPython(backfill_distinct_correlation_ids, migrations.RunPython.noop),
        migrations.AddField(
            model_name='manualtranslationjob',
            name='drive_root_folder_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='manualtranslationjob',
            name='final_artifact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chapter_translation_finals', to='editorial.pipelineartifact'),
        ),
        migrations.AddField(
            model_name='manualtranslationjob',
            name='final_sha256',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='manualtranslationjob',
            name='input_folder_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='manualtranslationjob',
            name='job_id',
            field=models.CharField(blank=True, default='', editable=False, max_length=160),
        ),
        migrations.AddField(
            model_name='manualtranslationjob',
            name='return_folder_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='manualtranslationjob',
            name='schema_version',
            field=models.CharField(default='gaiden_manual_translation_job_v1', max_length=64),
        ),
        migrations.AddField(
            model_name='manualtranslationjob',
            name='source_artifact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chapter_translation_sources', to='editorial.pipelineartifact'),
        ),
        migrations.AddField(
            model_name='manualtranslationjob',
            name='split_manifest',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='manualtranslationjob',
            name='split_strategy',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='manualtranslationjob',
            name='splitter_version',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='manualtranslationjob',
            name='translation_mode',
            field=models.CharField(choices=[('translate', 'Traduzir'), ('modernize_2026', 'Modernizar EN-US 2026')], default='translate', max_length=24),
        ),
        migrations.AddField(
            model_name='manualtranslationjob',
            name='validation_report',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='manualtranslationjob',
            name='status',
            field=models.CharField(choices=[('EXPORTED', 'Aguardando retorno'), ('IMPORTED', 'Tradução importada'), ('FAILED', 'Falha recuperável'), ('SPLIT_PENDING', 'Split pendente'), ('SPLITTING', 'Separando capítulos'), ('SPLIT_REVIEW_REQUIRED', 'Split requer revisão'), ('SPLIT_VALIDATED', 'Split validado'), ('DRIVE_EXPORTING', 'Exportando ao Drive'), ('DRIVE_READY', 'Drive pronto'), ('TRANSLATION_IN_PROGRESS', 'Tradução em andamento'), ('PARTIAL_RETURN', 'Retorno parcial'), ('RETURNS_READY', 'Retornos prontos'), ('VALIDATING_RETURNS', 'Validando retornos'), ('MERGE_READY', 'Merge liberado'), ('MERGING', 'Executando merge'), ('MERGED', 'Merge concluído'), ('VALIDATED', 'Manuscrito validado'), ('COMPLETED', 'Tradução pronta'), ('FAILED_RETRYABLE', 'Falha recuperável v2'), ('CONFLICT', 'Conflito'), ('REJECTED', 'Rejeitado')], default='EXPORTED', max_length=32),
        ),
        migrations.AddConstraint(
            model_name='manualtranslationjob',
            constraint=models.UniqueConstraint(condition=models.Q(('job_id', ''), _negated=True), fields=('job_id',), name='pipeline_manual_translation_job_id_unique'),
        ),
        migrations.AddField(
            model_name='translationjobevent',
            name='translation_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='pipeline.manualtranslationjob'),
        ),
        migrations.AddField(
            model_name='translationunit',
            name='translation_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='pipeline.manualtranslationjob'),
        ),
        migrations.AddField(
            model_name='translationjobevent',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='pipeline.translationunit'),
        ),
        migrations.AddConstraint(
            model_name='translationunit',
            constraint=models.UniqueConstraint(fields=('translation_job', 'unit_id'), name='pipeline_translation_unit_job_unit_unique'),
        ),
        migrations.AddConstraint(
            model_name='translationunit',
            constraint=models.UniqueConstraint(fields=('translation_job', 'sequence'), name='pipeline_translation_unit_job_sequence_unique'),
        ),
    ]
