# Generated by Django 5.2.10 on 2026-01-19 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('AUTHOR', 'Autor'), ('TRANSLATOR', 'Tradutor'), ('EDITOR', 'Editor'), ('ADAPTER', 'Adaptador')], default='AUTHOR', max_length=20)),
            ],
            options={
                'db_table': 'contributor',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('native_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'language',
            },
        ),
        migrations.CreateModel(
            name='Seal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'seal',
            },
        ),
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher', models.CharField(blank=True, max_length=255)),
                ('edition_year', models.IntegerField(blank=True, null=True)),
                ('raw_source_path', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('main_contributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='editions_main', to='editorial.contributor')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='editions', to='editorial.language')),
                ('seal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='editions', to='editorial.seal')),
            ],
            options={
                'db_table': 'edition',
            },
        ),
        migrations.CreateModel(
            name='EditionPipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stage', models.CharField(choices=[('RAW', 'Original (raw)'), ('NORMALIZED', 'Normalizado'), ('SPLIT', 'Split'), ('CHUNKED', 'Chunked'), ('TRANSLATED', 'Traduzido'), ('REFINED', 'Refine'), ('MERGED', 'Merge'), ('POLISHED', 'Polish (Codex)'), ('MIOLO_MD', 'Miolo MD'), ('FINAL_MD', 'MD Final'), ('DONE', 'Finalizado')], default='RAW', max_length=20)),
                ('raw_at', models.DateTimeField(blank=True, null=True)),
                ('normalized_at', models.DateTimeField(blank=True, null=True)),
                ('split_at', models.DateTimeField(blank=True, null=True)),
                ('chunked_at', models.DateTimeField(blank=True, null=True)),
                ('translated_at', models.DateTimeField(blank=True, null=True)),
                ('refined_at', models.DateTimeField(blank=True, null=True)),
                ('merged_at', models.DateTimeField(blank=True, null=True)),
                ('polished_at', models.DateTimeField(blank=True, null=True)),
                ('miolo_md_at', models.DateTimeField(blank=True, null=True)),
                ('final_md_at', models.DateTimeField(blank=True, null=True)),
                ('last_log', models.TextField(blank=True)),
                ('edition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline', to='editorial.edition')),
            ],
            options={
                'db_table': 'edition_pipeline',
            },
        ),
        migrations.CreateModel(
            name='EditionText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.TextField(blank=True)),
                ('normalized_text', models.TextField(blank=True)),
                ('raw_path', models.CharField(blank=True, max_length=500)),
                ('normalized_path', models.CharField(blank=True, max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('edition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='editorial.edition')),
            ],
            options={
                'db_table': 'edition_text',
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('publisher', models.CharField(blank=True, max_length=255)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('is_public_domain', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='works_as_author', to='editorial.contributor')),
                ('original_language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='works_original', to='editorial.language')),
            ],
            options={
                'db_table': 'work',
            },
        ),
        migrations.AddField(
            model_name='edition',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editions', to='editorial.work'),
        ),
        migrations.AlterUniqueTogether(
            name='edition',
            unique_together={('work', 'language', 'seal')},
        ),
    ]
