# Generated by Django 5.2.10 on 2026-01-19 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editorial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='editionpipeline',
            name='translation_language',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
