# Generated by Django 5.2.10 on 2026-01-20 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editorial', '0003_edition_frontmatter_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edition',
            name='country',
            field=models.CharField(choices=[('Brasil', 'Brasil'), ('Brazil', 'Brazil'), ('Brazile', 'Brazile')], default='Brasil', max_length=100),
        ),
    ]
