# Generated by Django 5.2.10 on 2026-01-20 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editorial', '0007_editionpipeline_md_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='edition',
            name='cover_filepath',
            field=models.CharField(blank=True, default='', help_text='Path inside the project (e.g., data/covers/book_0001/en/cover.jpg).', max_length=500),
        ),
    ]
