# Generated by Django 5.2.10 on 2026-01-20 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editorial', '0008_edition_cover_filepath'),
    ]

    operations = [
        migrations.AddField(
            model_name='editionpipeline',
            name='frontmatter_language',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='editionpipeline',
            name='frontmatter_locked',
            field=models.BooleanField(default=False),
        ),
    ]
