# Generated by Django 5.2.10 on 2026-01-21 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editorial', '0009_editionpipeline_frontmatter_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='edition',
            name='about_contributor_template',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='edition',
            name='about_edition_template',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='edition',
            name='copyright_template',
            field=models.TextField(default='Title\n{title}\nSubtitle\n{subtitle}\nAuthor\n{author}\nAdapter\n{adapter}\nPublication year\n{year}\n\nCopyright © {year} {author}.\nPublic Domain in the United States and other territories.\n\nThis modern version of *{title}* was produced under the {imprint} imprint.\n{imprint} is a registered trademark of RinoBooks.\n\nPublisher: {publisher}\nAll rights reserved © RinoBooks.\n{city}, {country} — {year}\n'),
        ),
        migrations.AddField(
            model_name='edition',
            name='editor',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='edition',
            name='frontispiece_template',
            field=models.TextField(default='{title}\nby {author}\n\nModern {language} Edition\nadapted by {adapter}\n\n{imprint}\n{city}, {country} · {year}'),
        ),
        migrations.AddField(
            model_name='edition',
            name='translator',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
