# Generated by Django 5.2.10 on 2026-01-21 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editorial', '0010_edition_about_contributor_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='edition',
            name='lock_polish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='edition',
            name='lock_refine',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='edition',
            name='lock_translate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='edition',
            name='miolo_source_stage',
            field=models.CharField(blank=True, choices=[('', 'AUTO'), ('translate', 'translate'), ('refine', 'refine'), ('polish', 'polish')], default='', max_length=20),
        ),
    ]
