# Generated by Django 5.2.10 on 2026-01-21 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editorial', '0011_edition_lock_polish_edition_lock_refine_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_code', models.CharField(db_index=True, max_length=200)),
                ('language_code', models.CharField(db_index=True, max_length=20)),
                ('stage', models.CharField(choices=[('raw', 'RAW'), ('normalize', 'NORMALIZE'), ('split', 'SPLIT/CHUNK'), ('translate', 'TRANSLATE'), ('refine', 'REFINE'), ('polish', 'POLISH'), ('miolo', 'MIOLO'), ('frontmatter', 'FRONTMATTER'), ('build', 'BUILD'), ('epub', 'EPUB'), ('pdf', 'PDF'), ('cover', 'COVER')], db_index=True, max_length=50)),
                ('relpath', models.TextField()),
                ('filename', models.CharField(db_index=True, max_length=255)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('mtime_iso', models.CharField(default='', max_length=40)),
                ('exists', models.BooleanField(default=True)),
                ('is_candidate', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('work_code', 'language_code', 'stage', 'relpath')},
            },
        ),
    ]
