# Generated by Django 5.2.11 on 2026-03-13 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editorial', '0012_pipelineartifact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edition',
            name='copyright_template',
            field=models.TextField(default='Title:\n{title}\n\nSubtitle:\n{subtitle}\n\nAuthor:\n{author}\n\nAdapter:\n{adapter}\n\nEditor:\n{editor}\n\nPublication Year:\n{year}\n\nThe original work, *{title}* by {author},\nis in the public domain worldwide.\n\nCopyright © {year} RinoBooks.\n\nThis modern edition, including translation, adaptation,\nand editorial material, is copyrighted by RinoBooks.\n\nThis edition of *{title}*\nwas produced under the {imprint} imprint.\n\n{imprint} is a registered trademark of RinoBooks.\n\nPublisher:\n{imprint}\n\nAll rights reserved.\n\n{city}, {country} — {year}\n'),
        ),
    ]
