# Generated by Django 5.2.10 on 2026-01-27 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editorial', '0013_pipelineartifact_status_sha256'),
        ('editorial', '0014_edition_language_variant'),
    ]

    operations = [
    ]
