# Generated by Django 5.2.11 on 2026-03-27 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editorial', '0015_alter_edition_copyright_template_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='editionpipeline',
            name='build_outdated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='editionpipeline',
            name='editorial_changed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='editionpipeline',
            name='last_built_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='editionpipeline',
            name='last_editorial_update_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='edition',
            name='imprint_name',
            field=models.CharField(choices=[('RinoBooks', 'RinoBooks'), ('Wrecked Alien Machine', 'Wrecked Alien Machine')], default='RinoBooks', max_length=100),
        ),
        migrations.AlterField(
            model_name='edition',
            name='language_code',
            field=models.CharField(choices=[('en', 'English'), ('pt-br', 'Português (Brasil)'), ('es', 'Español'), ('de', 'Deutsch'), ('it', 'Italiano'), ('fr', 'Français')], default='en', max_length=10),
        ),
        migrations.AlterField(
            model_name='edition',
            name='seal_name',
            field=models.CharField(choices=[('MantaQuest', 'MantaQuest'), ('Wrecked Alien Machine', 'Wrecked Alien Machine')], default='MantaQuest', max_length=100),
        ),
        migrations.CreateModel(
            name='EditionBuild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=10)),
                ('build_version', models.IntegerField()),
                ('build_type', models.CharField(choices=[('initial', 'Initial'), ('rebuild', 'Rebuild')], default='initial', max_length=20)),
                ('build_path', models.CharField(blank=True, default='', max_length=500)),
                ('epub_path', models.CharField(blank=True, default='', max_length=500)),
                ('pdf_path', models.CharField(blank=True, default='', max_length=500)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='build_history', to='editorial.edition')),
            ],
            options={
                'db_table': 'edition_build',
                'ordering': ['-build_version', '-created_at'],
                'unique_together': {('edition', 'language_code', 'build_version')},
            },
        ),
    ]
