# Generated by Django 5.2.11 on 2026-08-03 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editorial', '0017_editionpipeline_last_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='editionbuild',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='editionbuild',
            name='artifact_sha256',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='editionbuild',
            name='artifact_size_bytes',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='editionbuild',
            name='artifact_source',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='editionbuild',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='editionbuild',
            name='is_final',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='editionbuild',
            name='locale',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='editionbuild',
            name='official_body_path',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='editionbuild',
            name='official_body_sha256',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='editionbuild',
            name='status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not started'), ('IN_PROGRESS', 'In progress'), ('VALIDATING', 'Validating'), ('READY_FOR_APPROVAL', 'Ready for approval'), ('DONE', 'Done'), ('FAILED', 'Failed'), ('OUTDATED', 'Outdated')], default='NOT_STARTED', max_length=30),
        ),
        migrations.AddField(
            model_name='editionbuild',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='editionbuild',
            name='validation_passed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='EditionBuildAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(db_index=True, max_length=50)),
                ('actor', models.CharField(blank=True, default='system', max_length=150)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='editorial.editionbuild')),
            ],
            options={
                'db_table': 'edition_build_audit_event',
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
