# Generated by Django 5.2.10 on 2026-01-30 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editorial', '0018_edition_copyright_holder_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditionBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('frontispiece', 'Frontispício'), ('copyright', 'Copyright'), ('about_edition', 'About this Edition'), ('introduction', 'Introdução'), ('epilogue', 'Epílogo')], max_length=32)),
                ('text_md', models.TextField(blank=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='editorial.edition')),
            ],
            options={
                'unique_together': {('edition', 'block_type')},
            },
        ),
    ]
