# Generated by Django 5.2.11 on 2026-08-03 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editorial', '0018_editionbuild_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='editionbuild',
            name='validation_report',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
