# Generated by Codex on 2026-02-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("editorial", "0019_editionblock"),
    ]

    operations = [
        migrations.AddField(
            model_name="work",
            name="subtitle",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="work",
            name="enabled_languages",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="work",
            name="source_format",
            field=models.CharField(choices=[("TXT", "TXT"), ("MD", "MD")], default="TXT", max_length=10),
        ),
        migrations.AddField(
            model_name="work",
            name="notes",
            field=models.TextField(blank=True),
        ),
    ]
