# Generated by Django 5.2.11 on 2026-08-24 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editorial', '0020_work_source_provenance_runtime_compat'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelineartifact',
            name='sha256',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='pipelineartifact',
            name='stage',
            field=models.CharField(choices=[('raw', 'RAW'), ('normalize', 'NORMALIZE'), ('heading_clean', 'HEADING CLEAN'), ('split', 'SPLIT/CHUNK'), ('translate', 'TRANSLATE'), ('translation_final', 'TRANSLATION FINAL'), ('refine', 'REFINE'), ('polish', 'POLISH'), ('miolo', 'MIOLO'), ('frontmatter', 'FRONTMATTER'), ('build', 'BUILD'), ('epub', 'EPUB'), ('pdf', 'PDF'), ('cover', 'COVER')], db_index=True, max_length=50),
        ),
    ]
