# Generated by Django 5.2.10 on 2026-02-06 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editorial', '0020_work_projects_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edition',
            name='language_code',
            field=models.CharField(choices=[('en', 'English'), ('pt-br', 'Português (Brasil)'), ('es', 'Español'), ('de', 'Deutsch'), ('fr', 'Français'), ('it', 'Italiano')], default='en', max_length=10),
        ),
        migrations.AlterField(
            model_name='editionpipeline',
            name='current_stage',
            field=models.CharField(choices=[('RAW', 'Original (raw)'), ('NORMALIZED', 'Normalizado'), ('CHUNKED', 'Chunked'), ('TRANSLATED', 'Traduzido'), ('REFINED', 'Refine'), ('MERGED', 'Merge'), ('POLISHED', 'Polish (Codex)'), ('MIOLO_MD', 'Miolo MD'), ('FINAL_MD', 'MD Final'), ('DONE', 'Finalizado')], default='RAW', max_length=20),
        ),
        migrations.AlterField(
            model_name='pipelineartifact',
            name='stage',
            field=models.CharField(choices=[('raw', 'RAW'), ('normalize', 'NORMALIZE'), ('chunk', 'CHUNK'), ('translate', 'TRANSLATE'), ('merge_translate', 'MERGE_TRANSLATE'), ('refine', 'REFINE'), ('polish', 'POLISH'), ('miolo', 'MIOLO'), ('frontmatter', 'FRONTMATTER'), ('build', 'BUILD'), ('epub', 'EPUB'), ('pdf', 'PDF'), ('cover', 'COVER')], db_index=True, max_length=50),
        ),
    ]
