# Generated by Django 5.2.11 on 2026-08-24 21:57

from django.db import migrations, models


ADD_SHA256_COLUMN = """
ALTER TABLE editorial_pipelineartifact
    ADD COLUMN IF NOT EXISTS sha256 varchar(64) NOT NULL DEFAULT '';
CREATE INDEX IF NOT EXISTS editorial_pipelineartifact_sha256_compat_idx
    ON editorial_pipelineartifact (sha256);
"""


def ensure_sha256_column(apps, schema_editor):
    vendor = schema_editor.connection.vendor
    if vendor == "postgresql":
        schema_editor.execute(ADD_SHA256_COLUMN)
        return
    if vendor == "sqlite":
        table = "editorial_pipelineartifact"
        columns = {
            column.name
            for column in schema_editor.connection.introspection.get_table_description(
                schema_editor.connection.cursor(), table
            )
        }
        if "sha256" not in columns:
            schema_editor.execute(
                f"ALTER TABLE {table} ADD COLUMN sha256 varchar(64) NOT NULL DEFAULT ''"
            )
        schema_editor.execute(
            f"CREATE INDEX IF NOT EXISTS editorial_pipelineartifact_sha256_compat_idx "
            f"ON {table} (sha256)"
        )
        return
    raise RuntimeError("A migração de SHA-256 suporta somente PostgreSQL e SQLite.")


class Migration(migrations.Migration):

    dependencies = [
        ('editorial', '0020_work_source_provenance_runtime_compat'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    code=ensure_sha256_column,
                    reverse_code=migrations.RunPython.noop,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='pipelineartifact',
                    name='sha256',
                    field=models.CharField(blank=True, db_index=True, default='', max_length=64),
                ),
                migrations.AlterField(
                    model_name='pipelineartifact',
                    name='stage',
                    field=models.CharField(choices=[('raw', 'RAW'), ('normalize', 'NORMALIZE'), ('heading_clean', 'HEADING CLEAN'), ('split', 'SPLIT/CHUNK'), ('translate', 'TRANSLATE'), ('translation_final', 'TRANSLATION FINAL'), ('refine', 'REFINE'), ('polish', 'POLISH'), ('miolo', 'MIOLO'), ('frontmatter', 'FRONTMATTER'), ('build', 'BUILD'), ('epub', 'EPUB'), ('pdf', 'PDF'), ('cover', 'COVER')], db_index=True, max_length=50),
                ),
            ],
        ),
    ]
