# Generated by Django 5.2.10 on 2026-02-23 20:49

import editorial.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editorial', '0021_alter_edition_language_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='edition',
            name='book_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='edition',
            name='canonical_official_tag',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='edition',
            name='canonical_run_dir',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='edition',
            name='lang',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='edition',
            name='raw_materialized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='edition',
            name='raw_materialized_path',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='edition',
            name='raw_sha256',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='edition',
            name='raw_upload',
            field=models.FileField(blank=True, null=True, upload_to=editorial.models.edition_raw_upload_path),
        ),
        migrations.AddField(
            model_name='edition',
            name='status',
            field=models.CharField(choices=[('REGISTERED', 'Registered'), ('UPLOADED', 'Uploaded'), ('INGESTED', 'Ingested'), ('NORMALIZED', 'Normalized'), ('CHUNKED', 'Chunked'), ('TRANSLATED', 'Translated'), ('REFINED', 'Refined'), ('POLISHED', 'Polished'), ('CANONICAL_READY', 'Canonical Ready')], default='REGISTERED', max_length=32),
        ),
        migrations.AddField(
            model_name='edition',
            name='truth_frozen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='edition',
            name='truth_path',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='edition',
            name='truth_sha256',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
