# Generated by Django 5.2.10 on 2026-02-23 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editorial', '0022_edition_book_id_edition_canonical_official_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edition',
            name='status',
            field=models.CharField(choices=[('REGISTERED', 'Registered'), ('UPLOADED', 'Uploaded'), ('INGESTED', 'Ingested'), ('NORMALIZED', 'Normalized'), ('FIXED_TEXT', 'Fixed Text'), ('CHUNKED', 'Chunked'), ('TRANSLATED', 'Translated'), ('REFINED', 'Refined'), ('POLISHED', 'Polished'), ('CANONICAL_READY', 'Canonical Ready')], default='REGISTERED', max_length=32),
        ),
    ]
