from __future__ import annotations

from typing import Protocol


class DriveStoragePort(Protocol):
    remote: str
    inbox: str
    imported: str

    def list_folders(self, folder: str = "") -> list[dict]: ...
    def discover(self, folder: str, *, recursive: bool = True) -> tuple[str, list[dict]]: ...
    def download_to(self, remote_path: str, destination) -> None: ...
    def download_imported_to(self, canonical_path: str, destination) -> None: ...
    def promote_file(self, local_path, canonical_path: str, expected_sha256: str) -> str: ...
    def staging_directory(self): ...
