# Generated by Django 5.2.11 on 2026-06-13 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_module', '0002_collectionitem_upload_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='collection_kind',
            field=models.CharField(choices=[('novel_trilogy', 'Novel trilogy'), ('complete_novels', 'Complete novels'), ('collected_tales', 'Collected tales'), ('selected_stories', 'Selected stories'), ('thematic_collection', 'Thematic Collection'), ('collected_dialogues', 'Collected Dialogues'), ('selected_works', 'Selected Works'), ('complete_works', 'Complete Works'), ('collected_works', 'Collected Works'), ('anthology', 'Anthology'), ('omnibus', 'Omnibus'), ('mixed_collection', 'Mixed Collection'), ('cycle_collection', 'Cycle Collection'), ('companion_volume', 'Companion Volume')], max_length=50),
        ),
    ]
