"""
Django settings for gaiden_portal project.

Generated by 'django-admin startproject' using Django 5.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-)xkvqv2orvj!r)yisuq#-iisc4lrb_b#-676rwjz1*+0k=dw@&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "collections_module",
    "editorial",
    "pipeline",
    "web.author_studio.apps.AuthorStudioConfig",
    "web.writer.apps.WriterConfig",
    "web.intake.apps.IntakeConfig",
    "web.manual_ai.apps.ManualAIConfig",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'gaiden_portal.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'gaiden_portal.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


def _pg_config_missing() -> list[str]:
    required = ["PGHOST", "PGDATABASE", "PGUSER"]
    return [name for name in required if not os.getenv(name)]


missing = _pg_config_missing()
if missing:
    raise RuntimeError(
        "Gaiden requires PostgreSQL. Missing env vars: " + ", ".join(missing)
    )
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ["PGDATABASE"],
        "USER": os.environ["PGUSER"],
        "PASSWORD": os.environ.get("PGPASSWORD", ""),
        "HOST": os.environ["PGHOST"],
        "PORT": os.environ.get("PGPORT", "5432"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Django file fields share Gaiden's canonical storage root.
from gaiden.infrastructure.storage import storage_root

MEDIA_ROOT = storage_root()
MEDIA_URL = "/media/"

# Automated Intake Google Drive boundary. The configured rclone remote already
# points at the allowed "Gaiden Bookmaker" root in local development.
GAIDEN_DRIVE_REMOTE = os.environ.get("GAIDEN_DRIVE_REMOTE", "gaiden_drive")
GAIDEN_DRIVE_ROOT = os.environ.get("GAIDEN_DRIVE_ROOT", "").strip("/")
GAIDEN_DRIVE_INBOX = os.environ.get("GAIDEN_DRIVE_INBOX", "01_INBOX_RAW").strip("/")
GAIDEN_DRIVE_IMPORTED = os.environ.get("GAIDEN_DRIVE_IMPORTED", "02_IMPORTED_RAW").strip("/")
GAIDEN_INTAKE_ALLOWED_EXTENSIONS = tuple(
    value.strip().lower()
    for value in os.environ.get(
        "GAIDEN_INTAKE_ALLOWED_EXTENSIONS",
        ".epub,.txt,.md,.html,.htm,.docx,.rtf",
    ).split(",")
    if value.strip()
)
GAIDEN_INTAKE_MAX_FILE_SIZE = int(os.environ.get("GAIDEN_INTAKE_MAX_FILE_SIZE", str(100 * 1024 * 1024)))

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
