# Generated by Django 5.2.11 on 2026-07-14 18:28

import django.db.models.deletion
import gaiden.infrastructure.author_studio.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('canonical_name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('code', models.CharField(db_index=True, editable=False, max_length=12, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('canonical_title', models.CharField(max_length=500)),
                ('slug', models.SlugField(max_length=500)),
                ('code', models.CharField(db_index=True, editable=False, max_length=32, unique=True)),
                ('original_language', models.CharField(blank=True, default='', max_length=20)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('SOURCE_UPLOADED', 'Source Uploaded'), ('EXTRACTING', 'Extracting'), ('EXTRACTED', 'Extracted'), ('CANONICAL_READY', 'Canonical Ready'), ('NEEDS_REVIEW', 'Needs Review'), ('FAILED', 'Failed'), ('FROZEN', 'Frozen')], default='CREATED', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='works', to='author_studio.author')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='WorkSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, editable=False, max_length=48, unique=True)),
                ('original_filename', models.CharField(max_length=500)),
                ('stored_file', models.FileField(upload_to=gaiden.infrastructure.author_studio.storage.source_upload_path)),
                ('extension', models.CharField(max_length=20)),
                ('mime_type', models.CharField(blank=True, max_length=255)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('source_provider', models.CharField(default='UNKNOWN', max_length=50)),
                ('extraction_status', models.CharField(choices=[('PENDING', 'Pending'), ('STORED', 'Stored'), ('EXTRACTING', 'Extracting'), ('EXTRACTED', 'Extracted'), ('FAILED', 'Failed'), ('UNSUPPORTED_EXTRACTION', 'Unsupported Extraction')], default='PENDING', max_length=30)),
                ('extraction_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sources', to='author_studio.work')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CanonicalText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, editable=False, max_length=48, unique=True)),
                ('text_file', models.FileField(upload_to=gaiden.infrastructure.author_studio.storage.canonical_upload_path)),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('character_count', models.PositiveBigIntegerField(default=0)),
                ('word_count', models.PositiveBigIntegerField(default=0)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('READY', 'Ready'), ('NEEDS_REVIEW', 'Needs Review'), ('FROZEN', 'Frozen'), ('SUPERSEDED', 'Superseded')], default='DRAFT', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('work', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='canonical_text', to='author_studio.work')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='canonical_versions', to='author_studio.worksource')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='work',
            constraint=models.UniqueConstraint(fields=('author', 'canonical_title'), name='author_studio_unique_author_work'),
        ),
        migrations.AddConstraint(
            model_name='work',
            constraint=models.UniqueConstraint(fields=('author', 'slug'), name='author_studio_unique_author_slug'),
        ),
        migrations.AddConstraint(
            model_name='worksource',
            constraint=models.UniqueConstraint(fields=('work', 'sha256'), name='author_studio_unique_work_source'),
        ),
    ]
