# Generated by Django 5.2.11 on 2026-07-14 20:53

import django.db.models.deletion
import gaiden.infrastructure.author_studio.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author_studio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('STALE', 'Stale')], default='PENDING', max_length=20)),
                ('source_sha256', models.CharField(db_index=True, max_length=64)),
                ('chunk_count', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('canonical_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='split_runs', to='author_studio.canonicaltext')),
                ('work', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='split_run', to='author_studio.work')),
            ],
        ),
        migrations.CreateModel(
            name='WorkChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, editable=False, max_length=64, unique=True)),
                ('sequence', models.PositiveIntegerField()),
                ('unit_type', models.CharField(blank=True, max_length=30)),
                ('unit_title', models.CharField(blank=True, max_length=500)),
                ('text_file', models.FileField(upload_to=gaiden.infrastructure.author_studio.storage.chunk_upload_path)),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('character_count', models.PositiveIntegerField(default=0)),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('estimated_tokens', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('canonical_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='author_studio.canonicaltext')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='author_studio.work')),
            ],
            options={
                'ordering': ['sequence'],
                'constraints': [models.UniqueConstraint(fields=('work', 'sequence'), name='author_studio_unique_work_chunk_sequence')],
            },
        ),
    ]
